### PR TITLE
Photo Preview and Rubberband Widget Enhancements

### PR DESCRIPTION
**Pull request by ghost**
- Photo previews in all three 'viewer' widgets have been refactored
  into a new PhotoPreviewArea widget, which incorporates a QScrollArea
  displaying a QLabel containing the pixmap of the photo.
  PhotoPreviewArea supports automatic scaling of the displayed photo
  in response to resize events.
  - The previous ResizingPixmap class has been removed.
- MultiRubberBandedPixmap and RubberBandedPixmap have been renamed to
  MultiRubberBandedLabel and RubberBandedLabel to better reflect their
  inheritence from QLabel.
- MultiRubberBandedLabel and RubberBandedLabel have been updated to
  properly rescale their banded area(s) in response to rescaling from
  PhotoPreviewArea.
- RubberBandedWidget now supports size grips in all 4 corners and
  can be repositioned via mouse click-and-drag.
- RubberBandedLabel now allows a user to redraw the banded area via
  click-and-drag.
- Rubberbands can now be sized arbitrarily small.
- Adjusted the default sizes for some viewers to make better use of
  image scaling.
- Cleaned up/added documentation where necessary.

### CODE REVIEW

**Comment by ghost** [comment]
Ended up incorporating a bit more than originally planned into this, but I think you'll be pleased with the results overall. Hopefully it takes some of pain out of your workflow. As always, let me know of any nits or outright vetos and I'll be happy to accommodate.

**Comment by ghost** [comment]
Updated PR to address focus on selection views and scaling of rotated images.

**Comment by gthomsen** [comment]
Finally got a chance to review this.  I _really_ like the new region selection widget.  While the creation is centered about the double-click, the fact that one can double-click and drag a region is very useful.

A couple of issues I've noticed with this:

1) Labels in the PhotoRecordEditor window are no longer sized compactly.  Rather than each label being snug against it's neighbors there is now space surrounding each one.  Unclear if this causes the selection view/info area to be bigger than necessary which short changes the PhotoPreviewArea for landscape photos (see below).

2) The ArtRecordEditor should also have its focus explicitly set to the Art Type combo box to match the previous version's behavior.  Currently the PhotoPreviewArea has focus which (due to the landscape sizing issue below) causes panning rather than selection of the art type when using the keyboard.

3) The default size for a PhotoPreviewArea using a landscape photo is incorrect and requires panning.  Portrait-oriented photos are correct though.

4) The rubberband region can go outside of the preview area during creation (double click near an edge) or when single click-dragging the region.

5) I can't reliably reproduce this, though I thought I saw the rubberband box disappear in certain situations.  It may be that it was minimally sized and over a low contrast region of an image (effectively hidden) though I recall that behavior over a number of images - not all of them were low contrast.  That said, it doesn't happen often/reliably and one can simply double-click to create a new, default-sized region.  

As mentioned in other changes it would be _sweet_ to be able to use the scroll wheel to zoom in and out within a preview area, though that is outside of the scope of this PR.

**Comment by ghost** [comment]
Almost ready to push an update to this PR. Responses to your findings:

1) Played around with this and _think_ I've addressed it. Attached some images of what the label layout looks like now for PhotoRecordEditor (as well as PhotoRecordViewer cause why not). Let me know if I'm in the ballpark, and if not a visual aide could go a long way here. Bit of background: if its not obvious yet, I've been trying to phase out usage of setSizePolicy( Fixed, Fixed ) in favor of setting appropriate stretch factors within the corresponding QLayouts. From my experience, coercing Qt with fixed sizes leads to unintended side effects to other widget sizes or layouts. Better instead to gently suggest and let Qt do what it thinks is right.

2) Done

3) I can't seem to reproduce this in my environment, can you send me an example screenshot or some image filenames to try?

4) Done

5) The only thing that comes to mind here is an issue I noticed where rubberband regions can subtly move around while resizing a photo preview due precision loss when converting from QRectF to QRect, as the former can't be rendered via QPainter. Could be that downscaling effectively results in a rounded region rect height/width of 0 so its no longer rendered. That being said, don't think this should be a huge issue since you persist the normalized geometry.

photo_record_editor
photo_record_viewer

**Comment by gthomsen** [comment]
Responses:

1) Those look good and like they were before.
3) Turns out it was because the desired window size was larger than the X11 screen and Qt decided to favor space in the non-preview area in the PhotoRecordEditor.  Hopefully the changes made in #1 will reduce the overall size of the non-preview area and avoid panning.  I'll retest when you've pushed though it does beg the question of handling smaller screens.  Not a high priority, really.
5) Would it be hard to set a lower bound on the total size of the region, similar to what is in my master?  Certainly not 37-some odd pixels but maybe 5 to keep it big enough to grab and resize?  Again, not a high priority if we understand what causes it.

Things have quieted down on this end so I can test things again.  Let me know when you've pushed an update.

**Comment by ghost** [comment]
Ready to put a bow on this one if you are

**Comment by gthomsen** [comment]
Bow applied.

**Pull request merged**
